### PR TITLE
added debian packaging

### PR DESCRIPTION
**Pull request by hsteinhaus**
These packaging control files were simply generated by dh_make and probably still need some fine tuning. However, they generate a deb package that seems to work smoothly with Raspbian testing.

### CODE REVIEW

**Comment by sphaero** [comment]
Damn I should have looked here first. Just made debs as well :)
http://lola.z25.org/~arnaud/debian/zix25/gst-rpicamsrc_0.1-1.2_armhf.deb

**Comment by thaytan** [comment]
Thanks!

**Comment by tp-m** [comment]
I believe best practice is to call the debian/ directory something else than 'debian', such as 'debian.upstream' or somesuch, to avoid clashes in case debian or a debian-derivative actually wants to package it?

**Comment by thaytan** [comment]
No idea - I've never heard that.

**Pull request merged**
