### PR TITLE
Color balance interface support

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Comment by kaihendry** [comment]
Think I'm getting a build err now on Archlinux Arm btw http://s.natalian.org/2015-05-07/1430992603_952x1036.png

**Comment by philn** [comment]
But bcm_host is in the global LDFLAGS already, not sure to understand this error you're getting

**Comment by philn** [comment]
Can you try changing 

test_color_balance_LDADD =  $(GST_LIBS)

to

test_color_balance_LDADD =  $(RPI_LIBFLAGS) $(GST_LIBS)

?

**Comment by kaihendry** [comment]
Don't quite understand where to change that. Makefile is generated and fugly. :/

**Comment by philn** [comment]
change it in examples/Makefile.am and re-run autogen.sh

**Comment by thaytan** [comment]
You can also run 'make V=1' to get full output of the command line it's executing.

**Comment by kaihendry** [comment]
The change proposed by https://github.com/thaytan/gst-rpicamsrc/pull/27#issuecomment-99801844 worked btw.

    gst-launch-1.0 rpicamsrc bitrate=1000000 vflip=true !  video/x-h264,width=640,height=480,framerate=15/1 ! h264parse ! mpegtsmux name=muxer ! hlssink

Not sure if I need that bitrate, but the hlssinki mpegts files are like 75M. Blast.

    -rw-r--r--  1 root root  148 May  8 17:05 playlist.m3u8
    -rw-r--r--  1 root root 1.2M May  8 17:05 segment00000.ts
    -rw-r--r--  1 root root  75M May  8 17:20 segment00001.ts

**Comment by philn** [comment]
Thanks! I'll submit a pull request then :)

**Pull request merged**
